### ISSUE TITLE
BIG suggestion...

### ISSUE THREAD

**Issue by pattivaitaitis** [githubteacher/intro-to-github#23]
Please teach how to turn off email notification before doing the example comment exercise. This just killed my Outlook inbox, so I will be missing the rest of the training while I try to recover from the spam. 

Ugh.

**Comment by crichID** [comment]
@pattivaitaitis On the right hand side you will see an unsubscribe button! You can also choose to unwatch or ignore this repository!

![screenshot 2015-09-01 12 25 17](https://cloud.githubusercontent.com/assets/9950121/9609946/8c99b12e-50a4-11e5-936f-b671828e832d.png)
