### ISSUE TITLE
Advanced Github

### ISSUE THREAD

**Issue by ghost** [githubteacher/intro-to-github#3]
Are there any other sessions that can take a user from level 0 to level 10 or 9? I understand it is more of a hands on that will make you more familiar with Github but training sessions helps..

**Comment by crichID** [comment]
@imvivekkumbhar yes, we have different classes based on the level you would like to attain. Our [GitHub for Developers](https://training.github.com/classes/developers/) course covers 95% of the commands you will use in Git and GitHub. We also offer [free classes on various topics](https://training.github.com/classes/free/) to teach you the other 5%.

**Comment by ghost** [comment]
Perfect, i will look for those classes as well.. hope they are not just for developers

**Comment by ghost** [comment]
[GitHub](www.github.com) sample text

**Comment by crichID** [comment]
@imvivekkumbhar I would say they are not just for developers but they are for people who are more comfortable on the command line instead of desktop apps!
