### ISSUE TITLE
This is a demo Issue

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/intro-to-github#36]
Not only can you type plain text...
## Header
- [ ] item 1
- _item 2_

@crichID

**Comment by iamjoanne** [comment]
@githubteacher hello

**Comment by MayuraVerma** [comment]
test comment
this is answer

**Comment by bbblil** [comment]
@thomaslennan 
- [x] yes
- [ ] no

**Comment by inlinedave** [comment]
testing here too

**Comment by marcioarend** [comment]
[] Todo dobrar a meta ?

**Comment by brentd-smith** [comment]
#108 
I wonder what the pound sign + a number does?

**Comment by Shrijeeta** [comment]
hi
