### ISSUE TITLE
I'm interested in md files

### ISSUE THREAD

**Issue by garyzim** [githubteacher/intro-to-github#9]
I'm interested in learning more about the .md extension. Thanks!

**Comment by crichID** [comment]
@garyzim we have some great resources for learning markdown here: https://help.github.com/categories/writing-on-github/

**Comment by garyzim** [comment]
Why not "_markup_"?

**Comment by crichID** [comment]
@garyzim markdown is a markup language :wink:

**Comment by garyzim** [comment]
Ah!  okay, thanks crichID!
